### ISSUE TITLE
Bug in dowload file funtion

### ISSUE THREAD

**Issue by omarkhatibgg** [wraith4081/bunnycdn#4]
Hello, 

I was trying to dowload a file but it keeps failing, it seems you trying to convert the file to json in this line.

we should convert the response to blob

https://github.com/wraith4081/bunnycdn/blob/a16abb4951b7a51e4ba11415d1521196f4a4f80c/src/EdgeStorage.ts#L92

best Regards
Omar

**Comment by omarkhatibgg** [comment]
Hello again,

so I was wrong, we should handle both `json` and `blob` because the error is a json object 

so now I made it like this:

```ts
            if (status === 404) {
                const body = yield request.then(res => res.json());
                throw new Error(body.Message);
            }
            const body = yield request.then(res => res.blob());
            return body;


```

**Comment by wraith4081** [comment]
Hello, thank you for reporting the problem. At the moment I don't plan to update the old code, I will release a new version in the future and I will take this suggestion into consideration.
